
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class VentanaIngresar extends javax.swing.JFrame {

int hcomplementarias;
    public String tipoprofesor;
    public VentanaIngresar() {
        initComponents();
        
        abrirBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcedula = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtnombre = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtapellido = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtcarrera = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txthorasclase = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        listatipoprofesor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtHsemanales = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CEDULA:");

        jLabel2.setText("CARRERA:");

        jLabel3.setText("NOMBRES:");

        jLabel5.setText("APELLIDOS:");

        jScrollPane1.setViewportView(txtcedula);

        jScrollPane2.setViewportView(txtnombre);

        jScrollPane4.setViewportView(txtapellido);

        jScrollPane5.setViewportView(txtcarrera);

        jLabel8.setText("PROFESOR");

        jScrollPane6.setViewportView(txthorasclase);

        jLabel4.setText("HORAS CLASE:");

        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        listatipoprofesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiempo Parcial", "Medio tiempo", "Tiempo completo" }));
        listatipoprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listatipoprofesorActionPerformed(evt);
            }
        });

        jLabel6.setText("TIPO PROFESOR:");

        jScrollPane7.setViewportView(txtHsemanales);

        jLabel7.setText("HORAS SEMANALES:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(btnagregar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listatipoprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listatipoprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnagregar)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        abrirBD();
        if (listatipoprofesor.getSelectedItem()=="TiempoParcial") {
            tipoprofesor="Tiempo parcial";
           ProfesorTiempoParcial a=new ProfesorTiempoParcial(Integer.parseInt(txtHsemanales.getText()),txtcedula.getText() , txtnombre.getText(), txtapellido.getText(), Integer.parseInt(txthorasclase.getText()), txtcarrera.getText());
          hcomplementarias=a.horasComplementarias();
        }
        
        if (listatipoprofesor.getSelectedItem()=="Medio tiempo") {
            tipoprofesor="Medio tiempo";
           ProfesorMedioTiempo b=new ProfesorMedioTiempo(txtcedula.getText() , txtnombre.getText(), txtapellido.getText(), Integer.parseInt(txthorasclase.getText()), txtcarrera.getText());
           hcomplementarias=b.horasComplementarias();
           
        }
        
        if (listatipoprofesor.getSelectedItem()=="Tiempo completo") {
            tipoprofesor="Tiempo completo";
           ProfesorTiempoCompleto c=new ProfesorTiempoCompleto(txtcedula.getText() , txtnombre.getText(), txtapellido.getText(), Integer.parseInt(txthorasclase.getText()), txtcarrera.getText());
           hcomplementarias=c.horasComplementarias();
          
        }
        
 
        
        try {
             Statement sentencia=conexion.createStatement();
             ResultSet registros=sentencia.executeQuery("select * from PROFESOR");

                String CEDULA = txtcedula.getText();
               String NOMBRES =  txtnombre.getText();
               String APELLIDOS=txtapellido.getText();
                String CARRERA = txtcarrera.getText();
                String TIPOPROFESOR= tipoprofesor;
                int HORASCLASE=Integer.parseInt(txthorasclase.getText());
                int HORASCOMPLEMENTARIAS=hcomplementarias;
                
                
                System.out.printf("%s %s %s %s %s %d %d %n", CEDULA, NOMBRES, APELLIDOS, CARRERA, TIPOPROFESOR, HORASCLASE, HORASCOMPLEMENTARIAS);
                
                String sqlInsert= String.format("INSERT INTO PROFESOR VALUES('%s','%s','%s', '%s','%s', %d, %d)",CEDULA,NOMBRES,APELLIDOS,CARRERA,TIPOPROFESOR,HORASCLASE,HORASCOMPLEMENTARIAS);
                
                
               // "1153406959","Desarrollo de pensamiento computacional", 3, 2016);
                int r= sentencia.executeUpdate(sqlInsert);
               System.out.println("Se han modificado "+r+"registros");
           // }
             registros.close();
             conexion.close();
            
        } catch (SQLException exception) {
            System.out.println("Error al enviar consulta "+exception);
        
        }
        
        
        
    }//GEN-LAST:event_btnagregarActionPerformed

    private void listatipoprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listatipoprofesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listatipoprofesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIngresar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIngresar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JComboBox<String> listatipoprofesor;
    private javax.swing.JTextPane txtHsemanales;
    private javax.swing.JTextPane txtapellido;
    private javax.swing.JTextPane txtcarrera;
    private javax.swing.JTextPane txtcedula;
    private javax.swing.JTextPane txthorasclase;
    private javax.swing.JTextPane txtnombre;
    // End of variables declaration//GEN-END:variables
 Connection conexion=null;
     public void abrirBD(){
     
       try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            System.out.println("Driver cargado !!!");
        } catch (ClassNotFoundException cnfe) {
            System.out.println("Error al cargar Driver "+cnfe);   
        }
        
        try {
            String urlbd="jdbc:derby://localhost:1527/Profesores";
            conexion = DriverManager.getConnection(urlbd, "examen","examen");
             System.out.println("Conexion satisfactoria !!!");
        } catch (SQLException sqlex) {
            System.out.println("Error al establecer conexion a la BD: "+sqlex);
        }
     }
     
     public void agregarDatosBD(){}
     



}
